### ISSUE TITLE
Final list of topics to cover in first stage

### ISSUE THREAD

**Issue by vince19972** [vince19972/CodingBridge#2]
[Potential topics](https://github.com/vince19972/CodingBridge/wiki/Potential-Topics-for-Tutorials) are listed in wiki page.

I think it's better to focus on one (or two for max) topic in first stage, which is Dec 9.

**Comment by vince19972** [comment]
Hey @doodybrains, @jameshosken and @js6450 sorry for bothering. Just want to say that you guys provided great feedbacks last time in class. Really appreciate that! If possible, can you kindly take a quick look at the [potential topics](https://github.com/vince19972/CodingBridge/wiki/Potential-Topics-for-Tutorials) I listed, and pick one or two of which you think is most important for now? 

It's totally no pressure and no rush! Thank you 🙂

**Comment by js6450** [comment]
@vince19972 I think the list has a lot of very important topics that would be great to cover.

My picks would be What can programming languages do? and What's abstraction?

I think for someone that knows absolutely nothing about programming, these will be the most important things to know before doing anything further.

Always happy to help!

**Comment by vince19972** [comment]
@js6450 thank you so much!!!

**Comment by vince19972** [comment]
Final decision: Abstraction will be the main topic to cover in 1.0 version.

**Comment by vince19972** [comment]
Final final decision: Function and text editor are the main topics to cover in 1.0 version
